# Created by Jekyll Writer
title: Beautiful Testing
author: Ricky Ye
description: >
  Recording my testing life, Appreciate the beauty of Testing.
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
github_username: wenjoyee
markdown: kramdown
baseurl: ''

theme: jekyll-theme-cayman
